<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Heroes.Core\Heroes.Core.csproj" />
    <ProjectReference Include="..\Heroes.Console\Heroes.Console.csproj" />
    <ProjectReference Include="..\Heroes.Battle\Heroes.Battle.csproj" />
    <ProjectReference Include="..\Heroes.Adventure\Heroes.Adventure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\assets\units\*.json" Link="assets\units\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\schemas\unit.schema.json" Link="schemas\unit.schema.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
